/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Assert;
import org.junit.Test;

import java.util.List;

import static org.junit.Assert.*;

public class AddOperatorTest {
    @Test public void test() {
        AddOperator solution = new AddOperator();
        List<String> s =solution.addOperators("123",6);
        System.out.print(s.toString());
    }

    @Test public void testMaxProfit() {
        MaxProfit solution = new MaxProfit();
        int profit =solution.maxProfit(new int[]{4,8,6,10,3});
        System.out.println(profit);
    }

    @Test public void testNqueen() {
        Nqueen solution = new Nqueen();
        List<String []>  list= solution.solveNQueens(8);
        for(String [] item :list ){
            for(String i :item){
                System.out.println(i);
            }
            System.out.println("xxxxxxx");
        }
    }
}
